version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  target-branch: main
  schedule:
    interval: "monthly"
    time: "07:00"
    timezone: "Etc/GMT-4" # EDT/EST
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 2
  reviewers:
  - janbridley
  groups:
    actions-version:
      applies-to: version-updates
      patterns:
      - '*'
    actions-security:
      applies-to: security-updates
      patterns:
      - '*'
- package-ecosystem: "pip"
  directory: "/"
  target-branch: main
  schedule:
    interval: "monthly"
    time: "07:00"
    timezone: "Etc/GMT-4" # EDT/EST
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 2
  reviewers:
  - janbridley
  groups:
    pip-version:
      applies-to: version-updates
      patterns:
      - '*'
      update-types:
      - minor
      - patch
    pip-security:
      applies-to: security-updates
      patterns:
      - '*'
      update-types:
      - minor
      - patch
