ci:
  autoupdate_schedule: quarterly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.4.0'
    hooks:
      - id: end-of-file-fixer
        exclude: tests/sample_data
      - id: trailing-whitespace
        exclude: tests/sample_data
      - id: check-builtin-literals
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: requirements-txt-fixer
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        types_or: [ python, pyi, jupyter ]
        args: [ --fix ]
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]
  - repo: https://github.com/glotzerlab/fix-license-header
    rev: v0.4.1
    hooks:
      - id: fix-license-header
        name: Fix License Headers
        exclude: ^doc/|^tests/
        types_or: [python]
        args:
          - --license-file=LICENSE
          - --start=2
          - --num=1
          - --add=This file is from the parsnip project, released under the BSD 3-Clause License.
          - --keep-before=#!
