name: Run Tests

on:
  pull_request:
  push:
    branches:
      - "main"
      - "breaking"
  workflow_dispatch:


jobs:
  test_modern:
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    # Pull in the test script from run_tests and distribute python from matrix versions
    uses: ./.github/workflows/run_tests.yaml
    with:
      python-version: ${{ matrix.python-version }}

  test_legacy:
    needs: test_modern # Wait until modern version pass to run legacy tests.
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.6", "3.7", "3.8"]
    uses: ./.github/workflows/run_tests.yaml
    with:
      python-version: ${{ matrix.python-version }}
