name: Run Tests

#concurrency:
#  group: ${{ github.workflow }}-${{ github.ref }}
#  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - "main"
      - "breaking"
  workflow_dispatch:


jobs:
  modern_python_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.9, 3.10, 3.11, 3.12]
    # Pull in the test script from run_tests and distribute python from matrix versions
    uses: ./.github/workflows/run_tests.yaml
    with:
      python-version: ${{ matrix.python-version }}
